export const COLORS = {
  light: {
    background: '#ffffff',
    foreground: '#1e1e1e',
    muted: '#f5f5f5',
    muted_foreground: '#4e4e4e',
    popover: '#eaeaea',
    popover_foreground: '#1e1e1e',
    card: '#f0f0f0',
    card_foreground: '#1e1e1e',
    border: '#d6d6d6',
    input: '#eaeaea',
    primary: '#3498db',
    primary_foreground: '#ffffff',
    secondary: '#95a5a6',
    secondary_foreground: '#1e1e1e',
    accent: '#e74c3c',
    accent_foreground: '#ffffff',
    destructive: '#e74c3c',
    destructive_foreground: '#ffffff',
    ring: '#3498db',
  },
  dark: {
    background: '#000000',
    foreground: '#f5f5f5',
    muted: '#1e1e1e',
    muted_foreground: '#adb3bf',
    popover: '#252525',
    popover_foreground: '#eaeaea',
    card: '#858682',
    card_foreground: '#f5f5f5',
    border: '#6a5acd',
    input: '#6a5acd',
    primary: '#a7ff07',
    primary_foreground: '#ffffff',
    secondary: '#282828',
    secondary_foreground: '#e0e0e0',
    accent: '#7c83db',
    accent_foreground: '#ffffff',
    destructive: '#fb0f50',
    destructive_foreground: '#ffffff',
    ring: '#00aaff',
  },

  // FOREST GREEN
  forest_green: {
    background: '#1b3022',
    foreground: '#d9f8c4',
    muted: '#2a4230',
    muted_foreground: '#98c482',
    popover: '#354c39',
    popover_foreground: '#d9f8c4',
    card: '#3e5d46',
    card_foreground: '#d9f8c4',
    border: '#75c044',
    input: '#75c044',
    primary: '#6fba1c',
    primary_foreground: '#ffffff',
    secondary: '#435942',
    secondary_foreground: '#d9f8c4',
    accent: '#8ccf68',
    accent_foreground: '#ffffff',
    destructive: '#ff5e5e',
    destructive_foreground: '#ffffff',
    ring: '#75c044',
  },
  // OCEAN BREEZE
  ocean_breeze: {
    background: '#0e2439',
    foreground: '#e3f2fd',
    muted: '#1b4a6b',
    muted_foreground: '#aed7ff',
    popover: '#164461',
    popover_foreground: '#e3f2fd',
    card: '#1e5273',
    card_foreground: '#e3f2fd',
    border: '#47b8e0',
    input: '#47b8e0',
    primary: '#0eaaff',
    primary_foreground: '#ffffff',
    secondary: '#1d729c',
    secondary_foreground: '#e3f2fd',
    accent: '#5dd4ff',
    accent_foreground: '#ffffff',
    destructive: '#f8676a',
    destructive_foreground: '#ffffff',
    ring: '#0eaaff',
  },
  // SUNSET GLOW
  sunset: {
    background: '#2e1a1a',
    foreground: '#fddbcf',
    muted: '#4a2828',
    muted_foreground: '#ffa07a',
    popover: '#4e2929',
    popover_foreground: '#fddbcf',
    card: '#5a3030',
    card_foreground: '#fddbcf',
    border: '#ff4500',
    input: '#ff4500',
    primary: '#ff6347',
    primary_foreground: '#ffffff',
    secondary: '#ff8c69',
    secondary_foreground: '#2e1a1a',
    accent: '#ffa07a',
    accent_foreground: '#ffffff',
    destructive: '#ff4500',
    destructive_foreground: '#ffffff',
    ring: '#ff6347',
  },
  // ROYAL PURPLE
  royal_purple: {
    background: '#1a0e2a',
    foreground: '#eae2fc',
    muted: '#29144d',
    muted_foreground: '#a98ef8',
    popover: '#35185f',
    popover_foreground: '#eae2fc',
    card: '#482074',
    card_foreground: '#eae2fc',
    border: '#9c27b0',
    input: '#9c27b0',
    primary: '#6a1b9a',
    primary_foreground: '#ffffff',
    secondary: '#7e57c2',
    secondary_foreground: '#eae2fc',
    accent: '#b39ddb',
    accent_foreground: '#ffffff',
    destructive: '#e91e63',
    destructive_foreground: '#ffffff',
    ring: '#9c27b0',
  },
  // GOLDEN DESERT
  golden_desert: {
    background: '#3e2f1b',
    foreground: '#f7e1ba',
    muted: '#5a4322',
    muted_foreground: '#dab88b',
    popover: '#664e2a',
    popover_foreground: '#f7e1ba',
    card: '#7d6134',
    card_foreground: '#f7e1ba',
    border: '#c69c6d',
    input: '#c69c6d',
    primary: '#ffcc80',
    primary_foreground: '#ffffff',
    secondary: '#ffd54f',
    secondary_foreground: '#3e2f1b',
    accent: '#ffab40',
    accent_foreground: '#ffffff',
    destructive: '#f4511e',
    destructive_foreground: '#ffffff',
    ring: '#ffcc80',
  },
  // EMERALD GREEN
  emerald_green: {
    background: '#1b2e23',
    foreground: '#d6f6d6',
    muted: '#2a4531',
    muted_foreground: '#a0d4a0',
    popover: '#325f4a',
    popover_foreground: '#d6f6d6',
    card: '#3d5f4b',
    card_foreground: '#d6f6d6',
    border: '#4caf50',
    input: '#4caf50',
    primary: '#2e7d32',
    primary_foreground: '#ffffff',
    secondary: '#388e3c',
    secondary_foreground: '#d6f6d6',
    accent: '#689f38',
    accent_foreground: '#ffffff',
    destructive: '#d32f2f',
    destructive_foreground: '#ffffff',
    ring: '#2e7d32',
  },
};
