import { ErrorKey } from '@/common/i18n/error-messages';

export const BetterAuthCodes = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  FAILED_TO_CREATE_USER: 'FAILED_TO_CREATE_USER',
  FAILED_TO_CREATE_SESSION: 'FAILED_TO_CREATE_SESSION',
  FAILED_TO_UPDATE_USER: 'FAILED_TO_UPDATE_USER',
  FAILED_TO_GET_SESSION: 'FAILED_TO_GET_SESSION',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_EMAIL_OR_PASSWORD: 'INVALID_EMAIL_OR_PASSWORD',
  SOCIAL_ACCOUNT_ALREADY_LINKED: 'SOCIAL_ACCOUNT_ALREADY_LINKED',
  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',
  ID_TOKEN_NOT_SUPPORTED: 'ID_TOKEN_NOT_SUPPORTED',
  FAILED_TO_GET_USER_INFO: 'FAILED_TO_GET_USER_INFO',
  USER_EMAIL_NOT_FOUND: 'USER_EMAIL_NOT_FOUND',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL:
    'USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL',
  EMAIL_CAN_NOT_BE_UPDATED: 'EMAIL_CAN_NOT_BE_UPDATED',
  CREDENTIAL_ACCOUNT_NOT_FOUND: 'CREDENTIAL_ACCOUNT_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  FAILED_TO_UNLINK_LAST_ACCOUNT: 'FAILED_TO_UNLINK_LAST_ACCOUNT',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  USER_ALREADY_HAS_PASSWORD: 'USER_ALREADY_HAS_PASSWORD',
};

/** Maps Better Auth codes → internal keys */
const betterAuthErrorCodeMap: Record<string, ErrorKey> = {
  INVALID_EMAIL_OR_PASSWORD: 'INVALID_CREDENTIALS',
  INVALID_PASSWORD: 'INVALID_CREDENTIALS',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_TOKEN: 'INVALID_TOKEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL:
    'USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PASSWORD_TOO_SHORT: 'WEAK_PASSWORD',
  PASSWORD_TOO_LONG: 'WEAK_PASSWORD',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  NO_ACTIVE_SESSION: 'NO_ACTIVE_SESSION',
};

export function mapBetterAuthErrorToKey(code?: string): ErrorKey {
  if (!code) return 'INTERNAL_SERVER_ERROR';
  return (
    betterAuthErrorCodeMap[code] ??
    (code as ErrorKey) ??
    'INTERNAL_SERVER_ERROR'
  );
}
