const ORIGIN = process.env.EXPO_PUBLIC_API_BASE_URL;
const APP_VARIANT = process.env.EXPO_PUBLIC_APP_VARIANT;
const REVENUECAT_IOS_KEY = process.env.EXPO_PUBLIC_REVENUECAT_IOS_KEY;
const REVENUECAT_ANDROID_KEY = process.env.EXPO_PUBLIC_REVENUECAT_ANDROID_KEY;

export { APP_VARIANT, ORIGIN, REVENUECAT_IOS_KEY, REVENUECAT_ANDROID_KEY };
