export const PRAYER_CALCULATION_METHODS = [
  { id: 0, name: 'Jafari', translationKey: 'jafari' },
  { id: 1, name: 'Muslim World League', translationKey: 'muslimWorldLeague' },
  { id: 2, name: 'Islamic Society of North America', translationKey: 'isna' },
  { id: 3, name: 'Egyptian General Authority of Survey', translationKey: 'egyptian' },
  { id: 4, name: 'Umm Al-Qura University, Makkah', translationKey: 'ummAlQura' },
  { id: 5, name: 'University of Islamic Sciences, Karachi', translationKey: 'karachi' },
  { id: 6, name: 'Institute of Geophysics, University of Tehran', translationKey: 'tehran' },
  { id: 7, name: 'Shia Ithna-Ashari, Leva Institute, Qum', translationKey: 'jafari' },
  { id: 8, name: 'Gulf Region', translationKey: 'gulf' },
  { id: 9, name: 'Kuwait', translationKey: 'kuwait' },
  { id: 10, name: 'Qatar', translationKey: 'qatar' },
  { id: 11, name: 'Majlis Ugama Islam Singapura, Singapore', translationKey: 'singapore' },
  { id: 12, name: 'Union Organization islamic de France', translationKey: 'france' },
  { id: 13, name: 'Diyanet İşleri Başkanlığı, Turkey', translationKey: 'turkey' },
  { id: 14, name: 'Spiritual Administration of Muslims of Russia', translationKey: 'russia' },
  { id: 15, name: 'Moonsighting Committee Worldwide', translationKey: 'moonsighting' },
  { id: 16, name: 'Dubai (Unofficial)', translationKey: 'dubai' },
  { id: 17, name: 'Jabatan Kemajuan Islam Malaysia (JAKIM)', translationKey: 'jakim' },
  { id: 18, name: 'Tunisia', translationKey: 'tunisia' },
  { id: 19, name: 'Algeria', translationKey: 'algeria' },
  { id: 20, name: 'Kementerian Agama Republik Indonesia', translationKey: 'indonesia' },
  { id: 21, name: 'Morocco', translationKey: 'morocco' },
  { id: 22, name: 'Comunidate Islamica de Lisboa (Portugal)', translationKey: 'portugal' },
  {
    id: 23,
    name: 'Ministry of Awqaf, Islamic Affairs and Holy Places, Jordan',
    translationKey: 'jordan',
  },
];
